server:
   port: 9090
   
custom:
     id: 12
     name: Tarun Soni 

spring:
   application:
      name: employeeService
      
spring:
   cloud:
      config:
            uri: http://localhost:8090/
                 